# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: alpine:latest

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy

test: 
  stage: test
  script: npm i && npm run lint

build:
  stage: build
  script: docker build . -t charbot:latest

deploy:
  stage: deploy
  script: echo "Need to complete afterwards"